- name: RECIVER | Copy ansibullbot-receiver unit file
  template:
    src: systemd_ansibullbot_receiver.j2
    dest: /etc/systemd/system/ansibullbot-receiver.service
    owner: root
    group: root
    mode: 0644
  notify: restart ansibullbot-receiver
  tags:
    - ansibullbot
    - ansibullbot_receiver
    - ansibullbot_service
    - ansibullbot_update

- name: RECIVER | Install ansibullbot_receievr pip packages
  pip:
    name: "{{ ansibullbot_recevier_pip_packages }}"
    state: present
  tags:
    - ansibullbot
    - ansibullbot_receiver
    - ansibullbot_service
    - ansibullbot_update

- name: RECIVER | Start and enable ansibullbot-receiver
  systemd:
    name: ansibullbot-receiver
    daemon_reload: true
    enabled: true
    state: started
  tags:
    - ansibullbot
    - ansibullbot_service
    - ansibullbot_receiver
    - notest
