- name: Install apache
  yum:
    name: httpd
    state: present
  tags:
    - ansibullbot
    - ansibullbot_monitoring

- name: Copy monitoring web page
  copy:
    src: ansibot_status.cgi
    dest: /var/www/cgi-bin/
    owner: apache
    group: apache
    mode: 0755
  tags:
    - ansibullbot
    - ansibullbot_monitoring

- name: Start and enable httpd
  service:
    name: httpd
    state: started
  tags:
    - ansibullbot
    - ansibullbot_monitoring
