- name: Create initial log file
  copy:
    force: no
    dest: "{{ ansibullbot_log_path }}"
    content: ''
    owner: "{{ ansibullbot_user }}"
    group: "{{ ansibullbot_group }}"
  tags:
    - ansibullbot
    - ansibullbot_logs

- name: Setup log rotation
  template:
    src: logrotate_ansibullbot.j2
    dest: /etc/logrotate.d/ansibullbot
  tags:
    - ansibullbot
    - ansibullbot_logs
