- name: Create initial log file
  copy:
    force: no
    dest: "{{ ansibullbot_log_path }}"
    content: ''
    owner: "{{ ansibullbot_user }}"
    group: "{{ ansibullbot_group }}"
  tags:
    - ansibullbot
    - ansibullbot_logs

- name: Setup log rotation
  template:
    src: logrotate_ansibullbot.j2
    dest: /etc/logrotate.d/ansibullbot
  tags:
    - ansibullbot
    - ansibullbot_logs

- name: Create cron job to cleanup Shippable cache
  cron:
    cron_file: ansibullbot
    hour: 03
    minute: 11
    job: find {{ ansibullbot_cache_dir }} -type f -atime +{{ ansibullbot_cache_days_to_keep }} -exec rm -f '{}' ';'
  tags:
    - ansibullbot
    - ansibullbot_cache
    - ansibullbot_cron
