- name: MONITORING | Install apache
  yum:
    name: httpd
    state: present
  tags:
    - ansibullbot_monitoring

- name: MONITORING | Copy monitoring web page
  copy:
    src: "{{ ansibullbot_clone_path ~ '/scripts/ansibot_status.cgi' }}"
    dest: /var/www/cgi-bin/
    remote_src: true
    owner: apache
    group: apache
    mode: '0755'
  tags:
    - ansibullbot_monitoring

- name: MONITORING | Add httpd user account to {{ ansibullbot_group }} group
  user:
    name: apache
    groups: "{{ ansibullbot_group }}"
    append: true
  tags:
    - ansibullbot_monitoring

- name: MONITORING | Set permissions on ansibullbot home
  file:
    path: "{{ ansibullbot_home_dir }}"
    owner: "{{ ansibullbot_user }}"
    group: "{{ ansibullbot_group }}"
    mode: 'g+rx'
  tags:
    - ansibullbot_monitoring

- name: MONITORING | Set permissions on ansibullbot code checkout
  file:
    path: "{{ ansibullbot_clone_path }}"
    owner: "{{ ansibullbot_user }}"
    group: "{{ ansibullbot_group }}"
    recurse: true
    mode: 'g+r'

- name: MONITORING | Start and enable httpd
  service:
    name: httpd
    state: started
  tags:
    - ansibullbot_monitoring
