- name: Get latest revision
  git:
    repo: "{{ ansibullbot_repo_url }}"
    dest: "{{ ansibullbot_clone_path }}"
    force: yes
  become_user: "{{ ansibullbot_user }}"
  notify:
    - send slack message
    - restart ansibullbot
  tags:
    - ansibullbot
    - ansibullbot_git
    - ansibullbot_update

- name: Install Python requirements
  pip:
    requirements: "{{ ansibullbot_clone_path }}/requirements.txt"
  tags:
    - ansibullbot
    - ansibullbot_pip
    - ansibullbot_update
