- name: send slack message
  slack:
    msg: "{{ ansibullbot_slack_message }}"
    token: "{{ item }}"
  loop: "{{ ansibullbot_slack_token }}"

- name: restart ansibullbot
  systemd:
    name: ansibullbot
    daemon_reload: true
    state: restarted

- name: restart ansibullbot-receiver
  systemd:
    name: ansibullbot-receiver
    daemon_reload: true
    state: restarted

- name: reload caddy
  service:
    name: caddy
    state: reloaded
