- name: send slack message
  slack:
    msg: "{{ ansibullbot_slack_message }}"
    token: "{{ item }}"
  loop: "{{ ansibullbot_slack_token }}"
  tags:
    - notest

- name: restart ansibullbot
  systemd:
    name: ansibullbot
    daemon_reload: true
    state: restarted
  tags:
    - notest

- name: restart ansibullbot-receiver
  systemd:
    name: ansibullbot-receiver
    daemon_reload: true
    state: restarted
