- name: send slack message
  slack:
    msg: "{{ ansibullbot_slack_message }}"
    token: "{{ item }}"
  with_items: "{{ ansibullbot_slack_token }}"

- name: restart ansibullbot
  systemd:
    name: ansibullbot
    daemon_reload: yes
    state: restarted

- name: restart ansibullbot-receiver
  systemd:
    name: ansibullbot-receiver
    daemon_reload: yes
    state: restarted
