- hosts: all
  become: true

  vars_files:
    - vars.yml

  tasks:
    - name: Create centos group
      group:
        name: centos

    - name: Create centos user
      user:
        name: centos

    - import_role:
        name: repo_epel

    - import_role:
        name: caddy
      vars:
        caddy_download_custom_build: yes

    - import_role:
        name: ansibullbot
